# Generated by Django 5.0.4 on 2024-05-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_dttm", models.DateTimeField(verbose_name="date published")),
                (
                    "session_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sessions.session",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("text", models.TextField(max_length=4000)),
                (
                    "role",
                    models.CharField(
                        choices=[("US", "USER"), ("AS", "ASSISTANT")], max_length=2
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DE", "DE"), ("AC", "AC")], max_length=2
                    ),
                ),
                ("created_dttm", models.DateTimeField(verbose_name="date published")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webchat.chat"
                    ),
                ),
            ],
            options={
                "ordering": ["created_dttm"],
            },
        ),
    ]
